grafana:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    hosts:
      - grafana.localhost
    tls:
      - hosts:
          - grafana.localhost
        secretName: grafana-tls


