apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
spec:
  secretName: argocd-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  usages:
    - server auth
  dnsNames:
    - argocd.localhost
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
