traefik:
  logs:
    general:
      level: INFO
  globalArguments: []
  additionalArguments: []
  service:
    type: NodePort
    spec:
      externalTrafficPolicy: Cluster
  ports:
    web:
      hostPort: 80
      nodePort: 30080
    websecure:
      hostPort: 443
      nodePort: 30443
      traefik:
        expose: true

